services:
  - type: web
    name: htn-app
    env: node
    buildCommand: |
      cd frontend && npm install && npm run build && cd ..
      npm install
      cp -r frontend/dist/* backend/public/
    startCommand: node backend/server.js
    rootDir: ./
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18
