services:
  - type: web
    name: htn-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
    autoDeploy: true
    region: oregon
