services:
  - type: web
    name: htn-app
    env: node
    rootDir: ./
    buildCommand: |
      cd frontend && npm install && npm run build && cd ..
      cd backend && npm install && cd ..
      mkdir -p backend/public && cp -r frontend/dist/* backend/public/
    startCommand: node backend/server.js
    envVars:
      - key: NODE_VERSION
        value: 18
